// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSysF.Application.Infraestructure.Persistence;

#nullable disable

namespace NSysF.Application.Migrations
{
    [DbContext(typeof(NSysFDbContext))]
    [Migration("20220401030405_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NSysF.Application.Dominio.Entidades.FaltantesDet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id Consecutivo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)")
                        .HasComment("Cantidad solicitada");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasComment("El id del Cliente");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasComment("El id del Empleado");

                    b.Property<bool>("EsCadaUno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Si el precio es por unidad y no por caja");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("F")
                        .IsFixedLength()
                        .HasComment("Estatus del articulo del Faltante, F = Faltante, S = Surtido");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasComment("Fecha de Creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasComment("Fecha de Creacion");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasComment("Id del Catalogo de Marcas");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("Notas para el que va a surtir el reglon del Pedido");

                    b.Property<int>("ProdMaestroId")
                        .HasColumnType("int")
                        .HasComment("Id del catalogo de ProdMaestro");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClienteId" }, "IX_ClienteId");

                    b.HasIndex(new[] { "EmpleadoId" }, "IX_EmpleadoId");

                    b.HasIndex(new[] { "ClienteId", "EmpleadoId", "ProdMaestroId", "MarcaId", "Estatus" }, "IX_NoDup_FaltantesDet")
                        .IsUnique();

                    b.HasIndex(new[] { "ProdMaestroId" }, "IX_ProdMaestroId");

                    b.ToTable("FaltantesDet", (string)null);

                    b.HasComment("Tabla de faltantes de las Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
